language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

install:
    - composer update

script:
    # test with PHPUnit, higher supported version
    - vendor/bin/phpunit
    # run PHPUnit example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpunit && composer install && vendor/bin/phpunit); fi
    # run phpspec example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpspec && composer install && vendor/bin/phpspec run); fi
