language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

script:
  # test with PHPUnit ~5.7
  - if [[ ${TRAVIS_PHP_VERSION:0:3} = "5.6" || ${TRAVIS_PHP_VERSION:0:3} = "7.0" || ${TRAVIS_PHP_VERSION:0:3} = "7.1" ]]; then composer require --dev phpunit/phpunit:~5.7 && vendor/bin/phpunit; fi
  # test with PHPUnit ~6.5
  - if [[ ${TRAVIS_PHP_VERSION:0:3} = "7.2" ]]; then composer require --dev phpunit/phpunit:~6.5 && vendor/bin/phpunit; fi
  # test with PHPUnit ~7.5
  - if [[ ${TRAVIS_PHP_VERSION:0:3} = "7.3" || ${TRAVIS_PHP_VERSION:0:3} = "7.4" ]]; then composer require --dev phpunit/phpunit:~7.5 && vendor/bin/phpunit; fi
  # test with PHPUnit ~9.0
  - if [[ ${TRAVIS_PHP_VERSION:0:3} = "8.0" ]]; then composer require --dev phpunit/phpunit:~9.4 && vendor/bin/phpunit; fi
