language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

before_install:
    - phpunit --version
    - composer dump-autoload
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then composer require --dev phpunit/phpunit:^5.7.23; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then composer require --dev phpunit/phpunit:*; fi

script:
    # test with PHPUnit, higher supported version
    - vendor/bin/phpunit
    # run PHPUnit example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpunit && composer update && vendor/bin/phpunit); fi
    # run phpspec example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpspec && composer update && vendor/bin/phpspec run); fi
