language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  # - '8.0' is not available so far on Travis

script:
  # test with PHPUnit ~8.5
  - if [[ ${TRAVIS_PHP_VERSION:0:3} = "7.2" ]]; then composer require --dev phpunit/phpunit:~8.5 && vendor/bin/phpunit; fi
  # test with PHPUnit ~9.4
  - if [[ ${TRAVIS_PHP_VERSION:0:3} = "7.3" || ${TRAVIS_PHP_VERSION:0:3} = "7.4" || ${TRAVIS_PHP_VERSION:0:3} = "8.0" ]]; then composer require --dev phpunit/phpunit:~9.4 && vendor/bin/phpunit; fi
