language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

script:
    # test with PHPUnit, higher supported version
    - phpunit
    # run PHPUnit example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpunit && rm composer.lock && composer install && vendor/bin/phpunit); fi
    # run phpspec example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpspec && rm composer.lock && composer install && vendor/bin/phpspec run); fi
