language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'

services:
    - mysql

before_install:
    - rm composer.lock
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then composer require --dev phpunit/phpunit:^5.7.23; fi
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then composer require --dev phpunit/phpunit:*; fi
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
    # test with PHPUnit, higher supported version
    - vendor/bin/phpunit --testsuite 5.6-compat
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then vendor/bin/phpunit --testsuite 7.0-compat ; fi
    # run PHPUnit example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpunit && composer update && vendor/bin/phpunit); fi
    # run phpspec example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/phpspec && composer update && vendor/bin/phpspec run); fi
    # run Codeception example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/codeception && composer update && vendor/bin/codecept run unit); fi
    # run Core Suite example
    - (cd examples/wp-core-suite && composer update && vendor/bin/phpunit)
    # run wp-b
    - rowser example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/wp-browser && composer update && vendor/bin/codecept run unit && vendor/bin/codecept run integration); fi
    # run WooCommerce environment example
    - if [[ ${TRAVIS_PHP_VERSION:0:1} != "5" ]]; then (cd examples/woocommerce-env && composer update && vendor/bin/phpunit); fi
